name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 */10 * *' # Runs every 10 days at midnight
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called) through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://gmujtaba.com/feed" # Replace with your actual RSS feed URL
          max_post_count: 5
