name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *" # every 5 hours

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate `github-contribution-grid-snake.svg`
        uses: Platane/snk@v2.2.1
        with:
          github_user_name: iamgmujtaba
          svg_out_path: dist/github-contribution-grid-snake.svg
          color_snake: "#8A2BE2"      # Customize snake color
          color_dots: "#40E0D0"       # Customize dots color
          color_grid: "#444444"       # Customize grid color
          color_background: "none"    # Set background color
          speed: 2                    # Adjust speed (1-10)

      - name: Push SVG to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
