name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *" # every 5 hours

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation using Docker
        run: |
          docker run \
            --rm \
            -v ${{ github.workspace }}:/data \
            ghcr.io/platane/snk \
            generate \
            --user-name ${{ github.repository_owner }} \
            --output /data/dist/github-contribution-grid-snake.svg \
            --color_snake "#8A2BE2" \
            --color_dots "#40E0D0" \
            --color_grid "#444444" \
            --color_background "none" \
            --speed 2

      - name: Push SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
